name: CI for Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Python en el entorno
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Paso 3: Instalar las dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html selenium

      # Paso 4: Descargar el driver de Chrome
      - name: Set up ChromeDriver
        uses: Nanami7/setup-chromedriver@v1.0
        with:
          chromedriver-version: 'latest'

      # Paso 5: Ejecutar las pruebas
      - name: Run pytest
        run: |
          pytest --html=reports/report.html --self-contained-html

      # Paso 6: Cargar el reporte como artefacto
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: reports/report.html
