name: CI for Selenium Tests in Headless Mode

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Python en el entorno
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Paso 3: Instalar las dependencias de Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html selenium webdriver-manager

      # Paso 4: Instalar Chrome y ChromeDriver
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      # Paso 5: Ejecutar las pruebas en modo headless
      - name: Run pytest in headless mode
        run: |
          pytest --html=reports/report.html --self-contained-html

      # Paso 6: Cargar el reporte como artefacto
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: reports/report.html
