name: CI for Selenium Tests in Headless Mode

on:
  push:
    branches:
      - Develop
      - master
  pull_request:
    branches:
      - Develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Python en el entorno
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Paso 3: Instalar las dependencias de Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html selenium webdriver-manager

      # Paso 4: Instalar Chrome y ChromeDriver
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      # Paso 5: Instalar Xvfb (Virtual Framebuffer) para que Chrome se ejecute en modo headless
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      # Paso 6: Ejecutar las pruebas en modo headless con Xvfb
      - name: Run pytest in headless mode with Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          pytest --html=report.html --self-contained-html

      # Paso 7: Cargar el reporte HTML como artefacto
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: report.html
