name: Selenium Chrome Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Instalar Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Verificar que Chrome se haya instalado correctamente
      - name: Verify Chrome installation
        run: google-chrome --version

      - name: Run Selenium Tests with Chrome
        run: |
          pytest --headless
